### ISSUE TITLE
regarding hacktoberfest

### ISSUE THREAD

**Issue by DeadlyRanger** [Patel-Shailesh/hacktoberfest-2022#3]
hello sir , my pull request has been merged now , but on the hacktoberfest website it didnt shows that my request accepted it shows that not-accepted ,, pls provide some solution..

**Comment by Patel-Shailesh** [comment]
Hacktoberfest Page refreshes every 15 minutes. It'll show there
Just wait

**Comment by DeadlyRanger** [comment]
ohk !! thanks for solving my doubt

**Comment by Patel-Shailesh** [comment]
Message here once it shows in your hacktoberfest profile

I'll close this issue after that

**Comment by DeadlyRanger** [comment]
sure!!

**Comment by DeadlyRanger** [comment]
same message shows, not -accepted , i think may be u have to merged on main branch

**Comment by DeadlyRanger** [comment]
done now, Thanks !!
